version: 2.1

main_branches: &main_branches
  filters:
    branches:
      only:
        - master
        - dev
dev_branch: &dev_branch
  filters:
    branches:
      only:
        - dev
prod_branch: &prod_branch
  filters:
    branches:
      only:
        - master
commands:
  build:
    description: Build
    steps:
      - run:
          name: Rust install
          command: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y && source $HOME/.cargo/env || CARGO_ERROR = true
      - run:
          name: Npm install
          command: npm i
      - run:
          name: Build bundle
          command: npm run build
jobs:
  bundle:
    docker:
      - image: node:buster-slim
    description: Build project bundle
    steps:
      - checkout
      - build
  test:
    description: test project
    docker:
      - image: node:buster-slim
    steps:
      - checkout
      - build
      - run:
          name: Test project
          command: npm run tests
workflows:
  build_update_deploy:
    jobs:
      - bundle:
          <<: *main_branches
      - test:
          <<: *main_branches
          requires:
            - bundle
